name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        curl -O http://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-2.4.dmg &&
        hdiutil attach GDAL_Complete-2.4.dmg &&
        cd '/Volumes/GDAL Complete 2.4/' &&
        sudo installer -pkg 'Install GDAL Complete 2.4.pkg' -target "/";

